FROM node:alpine
WORKDIR /omega
EXPOSE 3000
RUN ["npx", "create-react-app", "."]
# RUN ["npm", "run", "build"]
# RUN ["npm", "install", "serve"]
# ENTRYPOINT ["serve", "-s", "."]
ENTRYPOINT ["npm", "start"]
