name: space

services:

  reactor:
    image: astrograzl/reactor:alpine
    restart: unless-stopped
    ports:
      - 3000:3000

  galaxy:
    image: astrograzl/galaxy:alpine
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - blackhole
    env_file:
      - .env

  blackhole:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_ONETIME_PASSWORD: yes
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_PASSWORD: ${DBPSWD}
      MYSQL_USER: ${DBUSER}
  
# networks:
# volumes:
# configs:
# secrets:
